[platformio]
default_envs = dayvault

[env:dayvault]
platform = ststm32
board = dayvault_l452rc
framework = arduino
board_build.flash_size = 256KB
board_build.ldscript = boards/stm32l452rc.ld
build_type = release
monitor_speed = 115200
build_flags =
    -Os
    -std=gnu++11
    -DARDUINO_GENERIC_L452RCTX
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -DHAL_DFSDM_MODULE_ENABLED
    -DUSB_CDC_TRANSMIT_TIMEOUT=10000
    -DUSE_USBD_COMPOSITE=1
    -DUSBD_CMPSIT_ACTIVATE_CDC=1
    -DUSBD_CMPSIT_ACTIVATE_MSC=1
    -DUSBD_COMPOSITE_USE_IAD=1
    -DUSBD_MAX_NUM_INTERFACES=3
    -IC:/Users/Administrator/.platformio/packages/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc
    -IC:/Users/Administrator/.platformio/packages/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Class/CompositeBuilder/Inc
    -IC:/Users/Administrator/.platformio/packages/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Class/CompositeBuilder/Src

[env:native]
platform = native
test_framework = unity
build_src_filter =
    -<*>
    +<RingBuf.cpp>
    +<WavFile.cpp>
    +<Cmd.cpp>
    +<Recorder.cpp>
test_build_src = true
