[platformio]
default_envs = dayvault

[env:dayvault]
platform = ststm32
board = dayvault_l452rc
framework = stm32cube
board_build.flash_size = 256KB
build_type = release
monitor_speed = 115200
build_flags =
    -Os
    -std=gnu99
    -DUSBD_ACTIVATE_CDC=1
build_src_filter =
    +<*>
    -<test/*>

[env:native]
platform = native
test_framework = unity
build_src_filter =
    -<*>
    +<usbproto.c>
test_build_src = true
