[platformio]
default_envs = dayvault

[env:dayvault]
platform = ststm32
board = dayvault_l452rc
framework = stm32cube
board_build.flash_size = 256KB
board_build.ldscript = boards/stm32l452rc.ld
build_type = release
monitor_speed = 115200
build_flags =
    -Os
    -std=gnu99
    -DUSBD_ACTIVATE_CDC=1
build_src_filter =
    +<*>
    -<test/*>

[env:native]
platform = native
test_framework = unity
build_src_filter =
    -<*>
    +<usbproto.c>
    +<wav.c>
    +<ringbuf.c>
    +<rec_mgr.c>
test_build_src = true

[env:arduino_test]
platform = ststm32
board = dayvault_l452rc
framework = arduino
board_build.flash_size = 256KB
build_flags =
    -Os
    -DARDUINO_GENERIC_L452RCTX
    -DUSBD_VID=0x0483
    -DUSBD_PID=0x5741
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
build_src_filter =
    -<*>
    +<../arduino_test/*>
